package giis.visualassert;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.List;

import org.junit.Test;

import giis.visualassert.portable.FileUtil;
import giis.visualassert.portable.JavaCs;

public class TestVisualAssert {
	/*
	 * What is being tested: no failure and failure for every feature. Each choice of:
	 * conditions on features: 
	 * - additional message
	 * - existing report subdir
	 * - use default report subdir 
	 * - use relative path 
	 * - do not show expected and actual 
	 * - soft differences
	 * - bright colors
	 * - specified dif filename
	 * conditions on self generated file
	 * - different instances
	 * - different executions same instance
	 * Framework usage is tested in separate class
	 */
	static String defaultFolder = JavaCs.DEFAULT_REPORT_SUBDIR;
	static String diffFile = "VisualAssertDiffFile.html";
	static String expected = "abc def ghi\nmno pqr s tu";
	static String actualNofail = "abc def ghi\nmno pqr s tu";
	static String actualFail = " abc DEF ghi\nother line\nmno pqr stu";
	static String expectedMessageShort = "Strings are different." + "\nThis is the additional message."
			+ "\n- Visual diffs at: " + diffFile;
	static String htmlDiffs = "<ins style=\"background:#e6ffe6;\">&nbsp;</ins>"
			+ "<span>abc </span><del style=\"background:#ffe6e6;\">def</del>"
			+ "<ins style=\"background:#e6ffe6;\">DEF</ins><span> ghi&para;"
			+ "<br></span><ins style=\"background:#e6ffe6;\">other&nbsp;line&para;" 
			+ "<br></ins><span>mno pqr s</span><del style=\"background:#ffe6e6;\">&nbsp;</del><span>tu</span>";

	@Test
	public void testNoFail() {
		VisualAssert va = new VisualAssert();
		va.assertEquals(expected, actualNofail);
	}

	@Test
	public void testFailAllConditionsFalse() {
		VisualAssert va = new VisualAssert(); // all config methods by default
		doFailAllConditionsFalse(va, "java.lang.AssertionError", "", "");
	}
	//Actual execution and assertions in a method that will be reused to test with frameworks
	public static void doFailAllConditionsFalse(VisualAssert va, String assertionException, String assertMessage, String expActMessage) {
		FileUtil.createDirectory(defaultFolder); // ensure folder exists
		FileUtil.fileWrite(FileUtil.getPath(defaultFolder, diffFile), "");
		try {
			va.assertEquals(expected, actualFail, "This is the additional message", diffFile);
			fail("this should fail");
		} catch (AssertionError e) {
			assertEquals(assertionException, e.getClass().getName()); //not a subclass of this exception
			//first transforms the file name in expected message to include the path
			String message=expectedMessageShort.replace(diffFile, FileUtil.getPath(JavaCs.DEFAULT_REPORT_SUBDIR, diffFile));
			message+=expActMessage;
			assertEquals(message, e.getMessage());
			assertEquals(htmlDiffs, FileUtil.fileRead(FileUtil.getPath(defaultFolder, diffFile)));
		}
	}

	@Test
	public void testFailAllConditionsTrue() {
		String tempReportPath = FileUtil.getPath(defaultFolder, "tmp-"+JavaCs.getUniqueId()); //folder does not exist
		VisualAssert va = new VisualAssert()
				.clearCurrentSequence()
				.setShowExpectedAndActual(true)
				.setUseLocalAbsolutePath(true)
				.setSoftDifferences(true)
				.setBrightColors(true)
				.setReportSubdir(tempReportPath);
		try {
			va.assertEquals(expected, actualFail);
			fail("this should fail");
		} catch (AssertionError e) {
			//get file and path of the generated diff file (only file in the folder)
			List<String> allFiles = FileUtil.getFileListInDirectory(tempReportPath);
			assertEquals(1, allFiles.size()); // only a file has been created
			String diffFileName = allFiles.get(0);
			
			String fullPath=FileUtil.getFullPath(FileUtil.getPath(tempReportPath, diffFileName));
			//on windows, back slash must be replaced by forward slash and full path start with slash
			if (fullPath.contains("\\"))
				fullPath="/" + fullPath.replace("\\", "/");
			String diffFileFullPath = "file://" + fullPath;

			String expectedMessageLong = "Strings are different." 
					+ "\n- Visual diffs at: " + diffFileFullPath 
					+ "\n- Expected: <" + expected + ">." 
					+ "\n- Actual: <" + actualFail + ">.";
			assertEquals(expectedMessageLong.replace("\r", ""), e.getMessage().replace("\r", ""));
			assertEquals(htmlDiffs.replace("&nbsp;", " ").replace("e6ffe6", "00ff00").replace("ffe6e6", "ff4000"),
					FileUtil.fileRead(FileUtil.getPath(tempReportPath, diffFileName)));
		}
	}
	
	@Test
	public void testAutogeneratedFileSequence() {
		String tempReportPath=FileUtil.getPath(defaultFolder, "tmp-"+JavaCs.getUniqueId());
		FileUtil.createDirectory(tempReportPath);
		VisualAssert va=new VisualAssert().setReportSubdir(tempReportPath);
		int initialSequence=JavaCs.getCurrentSequence();
		//Sequence number increments in succesive asserts with same va
		runFailSilently(va);
		assertTrue(FileUtil.fileRead(FileUtil.getPath(tempReportPath, "diff-" + String.valueOf(initialSequence) + ".html")).length()>0);
		runFailSilently(va);
		assertTrue(FileUtil.fileRead(FileUtil.getPath(tempReportPath, "diff-" + String.valueOf(initialSequence+1) + ".html")).length()>0);
		//a different va, sequence continues
		va=new VisualAssert().setReportSubdir(tempReportPath);
		runFailSilently(va);
		assertTrue(FileUtil.fileRead(FileUtil.getPath(tempReportPath, "diff-" + String.valueOf(initialSequence+2) + ".html")).length()>0);
	}
	private void runFailSilently(VisualAssert va) {
		try {
			va.assertEquals("abc", "def");
		} catch (AssertionError e) {
			//no action, but a file was generated
		}
	}

}
