version: 2
updates:
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: "/net"
    schedule:
      interval: daily
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 
