package giis.visualassert;

import java.util.LinkedList;

import org.bitbucket.cowwoc.diffmatchpatch.DiffMatchPatch;

import giis.portable.FileUtil;
import giis.portable.JavaCs;

/**
 * Assertion methods that generate an html file with the differences highlighting the additions and deletions;
 * useful when comparing large strings.
 */
public class VisualAssert {
	private boolean useLocalAbsolutePath=false;
	private boolean showExpectedAndActual=false;
	private String reportSubdir=JavaCs.DEFAULT_REPORT_SUBDIR;

	/**
	 * Sets the folder where the generated files with the differences are stored; if not set, files are stored by default in folder named 'target'
	 * @param reportSubdir the folder to store differences, relative to the current directory
	 * @return this object to allow fluent style
	 */
	public VisualAssert setReportSubdir(String reportSubdir) {
	    this.reportSubdir=reportSubdir;
	    return this;
	}
	/**
	 * If set to true, the link with the differences file will include an file url with the absolute path to the file;
	 * useful when running tests from a development environment that allows links in the messages (e.g. MS Visual Studio)
	 * @param useLocalAbsolutePath activates or deactivates this option
	 * @return this object to allow fluent style
	 */
	public VisualAssert setUseLocalAbsolutePath(boolean useLocalAbsolutePath) {
	    this.useLocalAbsolutePath=useLocalAbsolutePath;
	    return this;
	}
	/**
	 * If set to true, the assert message will include the whole content of the exepcted and actual strings that are compared
	 * @param showExpectedAndActual activates or deacctivates this option
	 * @return this object to allow fluent style
	 */
	public VisualAssert setShowExpectedAndActual(boolean showExpectedAndActual) {
	    this.showExpectedAndActual=showExpectedAndActual;
	    return this;
	}
	
	/**
	 * Asserts that two large strings are equal; 
	 * if they are not, generates an html file highlighting the additions and deletions
	 * and includes a link to the html file in the assert message.
	 * @param expected the expected string
	 * @param actual the value to compare against expected
	 */
	public void assertEquals(String expected, String actual) {
		assertEquals(expected, actual, "", "");
	}
	/**
	 * Asserts that two large strings are equal; 
	 * if they are not, generates an html file with the 'fileName' provided highlighting the additions and deletions
	 * and includes the specified 'message' and a link to the html file in the assert message.
	 * @param expected the expected string
	 * @param actual the value to compare against expected
	 * @param message additional message to be included
	 * @param fileName the name of the file with the differences, if empty, an autogenerated unique file name is used
	 */
	public void assertEquals(String expected, String actual, String message, String fileName) {
		if (!expected.equals(actual))
			throw new AssertionError(getAssertionMessage(expected, actual, message, fileName));
	}
	
	private String getAssertionMessage(String expected, String actual, String message, String fileName) {
		//Determina las diferencias en html usando diff match patch
		String htmlDiffs = getHtmlDiffs(expected, actual);
		
		//Asegura que existe la carpeta y guarda las diferencias en un html con nombre unico
		FileUtil.createDirectory(reportSubdir);
		String uniqueFileName =JavaCs.isEmpty(fileName) ?  "diff-" + JavaCs.getUniqueId() + ".html" : fileName;
		String uniqueFile = FileUtil.getPath(reportSubdir, uniqueFileName);
		FileUtil.fileWrite(uniqueFile, htmlDiffs);

		//Compone el mensaje html
		String fullMessage = "Strings are different.";
		if (!JavaCs.isEmpty(message))
			fullMessage += "\n" + message + ".";
		fullMessage += "\nVisual diffs at: " + getHtmlMarkup(uniqueFileName);
		if (showExpectedAndActual) {
			fullMessage += "\nExpected: <" + expected + ">.";
			fullMessage += "\nActual: <" + actual + ">.";
		} 
		return fullMessage;
	}
	private String getHtmlDiffs(String expected, String actual) {
		DiffMatchPatch dmp = new DiffMatchPatch();
		LinkedList<DiffMatchPatch.Diff> diff = dmp.diffMain(expected, actual);
		dmp.diffCleanupSemantic((LinkedList<DiffMatchPatch.Diff>)diff);
		return dmp.diffPrettyHtml(diff);
	}
    private String  getHtmlMarkup(String uniqueFileName) {
    	String path=uniqueFileName;
    	if (useLocalAbsolutePath) {
    		path = FileUtil.getPath(reportSubdir, uniqueFileName);
    		path = "file:///" + FileUtil.getFullPath(path);
    	}
    	return "<a href=\"" + path + "\">" + uniqueFileName + "</a>";
    }

}
