name: Test visual-assert Java and .NET
on: [push, pull_request]
jobs:
  test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java
    #if: ${{ false }}  # disable for now
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
      - name: Select Java Version
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          #cache: 'maven' (Now fails when loading the environment!!!)

      - name: Build and test
        run: mvn test -Dmaven.test.failure.ignore=true -U --no-transfer-progress
      - name: Generate surefire report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: test-report-java
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_test_failures: 'true'
 
      - if: always()
        name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-report-java-files
          #working-directory does not work here
          path: |
            java/target/site
            java/target/*.html
            java/target/tmp*/*.html
  test-net:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: net
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x'

      - name: Run test
        run: dotnet test --logger "trx;LogFileName=../../reports/visual-assert-report.trx" TestVisualAssert/TestVisualAssert.csproj

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: test-report-net
          #working-directory does not work here
          path: net/reports/visual-assert-report.trx
          reporter: dotnet-trx
          fail-on-error: 'true'
      - if: always()
        name: Publish test reports files
        uses: actions/upload-artifact@v2
        with:
          name: test-report-net-files
          #working-directory does not work here
          path: net/reports
