name: Test visual-assert Java
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java
    #if: ${{ false }}  # disable for now
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
      - name: Select Java Version
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          #cache: 'maven' (Ahora causa fallo al cargar el entorno!!!)

      - name: Build and test
        run: mvn test -Dmaven.test.failure.ignore=true -U --no-transfer-progress
      - name: Generate surefire report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: test-failure-report (ut, it)
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_test_failures: 'true'
 
      - if: always()
        name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-html
          path: java/target/site/surefire-report.html
