name: Test visual-assert .NET
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: net
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x'

      - name: Run test
        run: dotnet test --logger "trx;LogFileName=../../reports/visual-assert-report.trx" TestVisualAssert/TestVisualAssert.csproj

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: test-report
          path: reports/visual-assert-report.trx
          reporter: dotnet-trx
          fail-on-error: 'true'
      - if: always()
        name: Publish test reports files
        uses: actions/upload-artifact@v2
        with:
          name: test-report-files
          #working-directory does not work here
          path: net/reports
